ARTIFACT_BASE_URL=https://github.com/containerd/nerdctl/releases/download/v2.3.0

AARCH64_ARTIFACT=nerdctl-full-2.3.0-linux-arm64.tar.gz
AARCH64_256_DIGEST=45738e1180de55430b81930c91652d8a734384b0ad55a59d33f6e5a982c3ee55

X86_64_ARTIFACT=nerdctl-full-2.3.0-linux-amd64.tar.gz
X86_64_256_DIGEST=ecb3bc90d36131652f4ccc5ea7218bbf935cf95a836c13833e827f75a3841ed2

# These versions were read from the nerdctl-full archive above.
# PLEASE DO NOT UPDATE THESE MANUALLY
NERDCTL_VERSION=2.3.0
CONTAINERD_VERSION=2.3.0
RUNC_VERSION=1.4.2
BUILDKIT_VERSION=0.29.0
CNI_PLUGINS_VERSION=1.9.1
